name: Flask App Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    strategy:
      fail-fast: false
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Depenencies
        run: |
          python3 setup.py
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run Pytest
        run: pytest -v
        env:
          PYTHONPATH: .
